services:
  api:
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"